// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD21G2ZZK8wqeyEoKeSvoqcmfrx40MtUjw',
    appId: '1:320082352995:web:722139183f4eb685bed156',
    messagingSenderId: '320082352995',
    projectId: 'fir-form-b0399',
    authDomain: 'fir-form-b0399.firebaseapp.com',
    storageBucket: 'fir-form-b0399.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQWaKJE2VuvIn1g-O-l7Y2w3tMCAXmaiY',
    appId: '1:320082352995:android:1727810ce025908cbed156',
    messagingSenderId: '320082352995',
    projectId: 'fir-form-b0399',
    storageBucket: 'fir-form-b0399.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyXpc6dcdRqjsJz7Z7tiTcFAM-BQKHU_k',
    appId: '1:320082352995:ios:3df851eb85435760bed156',
    messagingSenderId: '320082352995',
    projectId: 'fir-form-b0399',
    storageBucket: 'fir-form-b0399.appspot.com',
    iosClientId: '320082352995-oe7giq74eh7tn632885rlmj0dn0bbr8r.apps.googleusercontent.com',
    iosBundleId: 'com.example.formulaire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyXpc6dcdRqjsJz7Z7tiTcFAM-BQKHU_k',
    appId: '1:320082352995:ios:39c08ada548f8617bed156',
    messagingSenderId: '320082352995',
    projectId: 'fir-form-b0399',
    storageBucket: 'fir-form-b0399.appspot.com',
    iosClientId: '320082352995-cudcqan0j6mffbgv4n6u148e5fpnsqld.apps.googleusercontent.com',
    iosBundleId: 'com.example.formulaire.RunnerTests',
  );
}
